/**
 * Tailwind can only detect class names that appear as complete, static
 * strings somewhere in the source. Building them at runtime with template
 * literals (e.g. `bg-${color}-100`) means the class is never generated by
 * the JIT compiler, so it silently does nothing in a production build.
 *
 * This map gives every color/tone combo we use a fully-written-out static
 * class string, so Tailwind picks it up no matter which one is chosen at
 * render time.
 */

export type AccentColor = "green" | "blue" | "teal" | "yellow" | "red" | "purple";

interface AccentTokens {
  iconBg: string;
  iconText: string;
  dot: string;
  text: string;
  ring: string;
  gradientFrom: string;
  gradientTo: string;
  glow: string;
}

export const ACCENTS: Record<AccentColor, AccentTokens> = {
  green: {
    iconBg: "bg-green-100",
    iconText: "text-green-600",
    dot: "bg-green-400",
    text: "text-green-600",
    ring: "ring-green-400/40",
    gradientFrom: "from-green-400",
    gradientTo: "to-green-500",
    glow: "rgba(16,185,129,0.45)",
  },
  blue: {
    iconBg: "bg-blue-100",
    iconText: "text-blue-600",
    dot: "bg-blue-400",
    text: "text-blue-600",
    ring: "ring-blue-400/40",
    gradientFrom: "from-blue-400",
    gradientTo: "to-blue-500",
    glow: "rgba(59,130,246,0.45)",
  },
  teal: {
    iconBg: "bg-teal-100",
    iconText: "text-teal-600",
    dot: "bg-teal-400",
    text: "text-teal-600",
    ring: "ring-teal-400/40",
    gradientFrom: "from-teal-400",
    gradientTo: "to-teal-500",
    glow: "rgba(20,184,166,0.45)",
  },
  yellow: {
    iconBg: "bg-yellow-100",
    iconText: "text-yellow-600",
    dot: "bg-yellow-400",
    text: "text-yellow-600",
    ring: "ring-yellow-400/40",
    gradientFrom: "from-yellow-400",
    gradientTo: "to-yellow-500",
    glow: "rgba(245,158,11,0.45)",
  },
  red: {
    iconBg: "bg-red-100",
    iconText: "text-red-600",
    dot: "bg-red-400",
    text: "text-red-600",
    ring: "ring-red-400/40",
    gradientFrom: "from-red-400",
    gradientTo: "to-red-500",
    glow: "rgba(239,68,68,0.45)",
  },
  purple: {
    iconBg: "bg-purple-100",
    iconText: "text-purple-600",
    dot: "bg-purple-400",
    text: "text-purple-600",
    ring: "ring-purple-400/40",
    gradientFrom: "from-purple-400",
    gradientTo: "to-purple-500",
    glow: "rgba(139,92,246,0.45)",
  },
};
